name: Deploy Yam ECS Fargate

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1 — Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2 — Config AWS
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # 3 — Login to ECR
      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # 4 — Build / Tag / Push Docker
      - name: Build, Tag and Push Docker image
        run: |
          cd yam-ecs-fargate-sample    # <<< IMPORTANT !!!
          IMAGE_TAG=v1
          ECR_URI=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/yam-ecs-fargate

          docker build -t $ECR_URI:$IMAGE_TAG .
          docker push $ECR_URI:$IMAGE_TAG

      # 5 — Terraform Deploy
      - name: Terraform Init / Apply
        working-directory: yam-ecs-fargate-sample/terraform
        run: |
          terraform init
          terraform apply -auto-approve -var="image_url=${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/yam-ecs-fargate:v1"
